### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells. 

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [96]:
# YOUR CODE HERE
# Create a list of numbers between 60 and 69 (inclusive)
numbers_between_60_and_69 = [num for num in range(60, 70)]
print(numbers_between_60_and_69)
#raise NotImplementedError()

[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [22]:
# YOUR CODE HERE
import math

count = 0
total = 0
squared_total = 0

while True:
    try:
        num = float(input("Enter a number (0 to stop): "))
        if num == 0:
            break
        count += 1
        total += num
        squared_total += num ** 2
    except ValueError:
        print("Invalid input. Please enter a valid number.")

if count == 0:
    print("No numbers entered.")
else:
    mean = total / count
    variance = (squared_total / count) - (mean ** 2)
    std_deviation = math.sqrt(variance)

    print(f"Mean: {mean}")
    print(f"Standard Deviation: {std_deviation}")
#raise NotImplementedError()

Enter a number (0 to stop):  0


No numbers entered.


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [24]:
# YOUR CODE HERE
l = [2, 3, -2, -7, 0, 2, 3]

odd_numbers = [num for num in l if num % 2 != 0]

for num in odd_numbers:
    print(num)
#raise NotImplementedError()

3
-7
3


##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [29]:
# YOUR CODE HERE
def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    for i in range(3, int(num**0.5) + 1, 2):
        if num % i == 0:
            return False
    return True

def get_n_primes(N):
    if N <= 0:
        return []

    prime_numbers = []
    num = 2

    while len(prime_numbers) < N:
        if is_prime(num):
            prime_numbers.append(num)
        num += 1

    return prime_numbers
#raise NotImplementedError()

In [30]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [43]:
# YOUR CODE HERE
def get_nth_fibonacci(N):
    if N < 0:
        raise ValueError("N must be a non-negative integer.")
    elif N == 0:
        return 0
    elif N == 1:
        return 1
    else:
        # Calculate the Nth Fibonacci number using recursion
        return get_nth_fibonacci(N - 1) + get_nth_fibonacci(N - 2)
#raise NotImplementedError()

In [44]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [45]:
# YOUR CODE HERE
def is_odd(num):
    return num % 2 != 0

def is_prime(num):
    if num <= 1:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    for i in range(3, int(num**0.5) + 1, 2):
        if num % i == 0:
            return False
    return True

def filter_list(input_list, predicate):
    filtered_list = []
    for element in input_list:
        if predicate(element):
            filtered_list.append(element)
    return filtered_list
#raise NotImplementedError()

In [46]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [48]:
# YOUR CODE HERE
def reduce(sequence, func, accumulator=None):
    # If accumulator is not provided, use the first element of the sequence
    if accumulator is None:
        if len(sequence) < 2:
            raise ValueError("Reduce of empty sequence with no initial value")
        accumulator = sequence[0]
        sequence = sequence[1:]

    for item in sequence:
        accumulator = func(accumulator, item)

    return accumulator

# Binary function for addition
def add(x, y):
    return x + y

# Binary function for product
def product(x, y):
    return x * y

# Binary function for string addition
def string_addition(x, y):
    return str(x) + str(y)

# Binary function for adding string lengths
def string_len_add(total_len, string):
    return total_len + len(string)
#raise NotImplementedError()

In [49]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [50]:
# YOUR CODE HERE
def reduce(sequence, func, accumulator=None):
    # If accumulator is not provided, use the first element of the sequence
    if accumulator is None:
        if len(sequence) < 2:
            raise ValueError("Reduce of empty sequence with no initial value")
        accumulator = sequence[0]
        sequence = sequence[1:]

    for item in sequence:
        accumulator = func(accumulator, item)

    return accumulator

# Binary function for counting odd elements
def count_odd(total_count, num):
    if num % 2 != 0:
        return total_count + 1
    return total_count

# Binary function for finding the maximum
def find_max(max_num, num):
    return max(max_num, num)

# Binary function for finding the longest string
def find_longest_string(longest, string):
    return string if len(string) > len(longest) else longest

#raise NotImplementedError()

In [52]:
# YOUR CODE HERE
# a. Count the number of odd elements in a list of integers
list_of_integers = [1, 2, 3, 4, 5, 6, 7]
count_odd_elements = reduce(list_of_integers, count_odd, 0)
assert count_odd_elements == 4
#raise NotImplementedError()

In [53]:
# b. Find the maximum of a list of integers
list_of_integers = [3, 8, 2, 11, 6, 5, 9]
maximum_value = reduce(list_of_integers, find_max)
assert maximum_value == 11

In [54]:
# c. Find the longest string in a list of strings
list_of_strings = ["apple", "banana", "cherry", "date", "fig"]
longest_string = reduce(list_of_strings, find_longest_string, "")
assert longest_string == "banana"

9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [56]:
# YOUR CODE HERE
import math

def pairwise_row_distance(matrix):
    N = len(matrix)
    D = [[0.0] * N for _ in range(N)]

    for i in range(N):
        for j in range(i, N):
            if i != j:
                distance = math.sqrt(sum((x - y) ** 2 for x, y in zip(matrix[i], matrix[j])))
                D[i][j] = distance
                D[j][i] = distance

    return D

def is_matrix(matrix):
    if not matrix:
        return False
    num_cols = len(matrix[0])
    return all(len(row) == num_cols for row in matrix)

def transpose(matrix):
    return [list(row) for row in zip(*matrix)]

# Test the pairwise_row_distance function
A = [[1, 0, 2], [0, 2, 1]]
D = pairwise_row_distance(A)
#raise NotImplementedError()

In [57]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
assert transpose(D) == D

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [58]:
# YOUR CODE HERE
class A:
    def __init__(self,value):
        self.value = value
    def print_value(self):
        print(self.value)
a = A(2)
a.print_value()
#raise NotImplementedError()

2


In [59]:
a = A("abc")
a.print_value()

abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [60]:
# YOUR CODE HERE
class B:
    def __init__(self, public_param, private_param):
        self.this_is_public = public_param
        self.__this_is_private = private_param
#raise NotImplementedError()

In [61]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [31]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True
True
False
True
True


In [32]:
print(issubclass(C, object))
print(issubclass(D, B))
print(issubclass(B, D))
print(issubclass(B, B))

True
True
False
True


instantiated#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [82]:
# YOUR CODE HERE
class Animal:
    def __init__(self, name, age=0):
        self.name = name
        self.age = age
        self.number_of_legs = 0

    def make_sound(self):
        pass

class Mammal(Animal):
    def __init__(self, name, age=0, fur_colors=None):
        super().__init__(name, age)
        self.fur_colors = fur_colors if fur_colors is not None else []

class Cat(Mammal):
    def make_sound(self):
        print(f"{self.name} the Cat says 'Meow!'")

class Dog(Mammal):
    def make_sound(self):
        print(f"{self.name} the Dog says 'Woof!'")

class Fish(Animal):
    def make_sound(self):
        print(f"{self.name} the Fish makes no sound")

class Eagle(Animal):
    def make_sound(self):
        print(f"{self.name} the Eagle screeches")





#raise NotImplementedError()

In [81]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

Could not initialize an animal: Mammal.__init__() got an unexpected keyword argument 'fur'


#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [83]:

import numpy as np

In [85]:

def standardize(X):
    # YOUR CODE HERE
    row_means = np.mean(X, axis=1, keepdims=True)
    column_stddevs = np.std(X, axis=0, keepdims=True)
   # raise NotImplementedError()

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [86]:
import numpy as np

In [93]:
def normalize(X):
    # YOUR CODE HER
  # Calculate the minimum and maximum values of the array
    X_min = np.min(X)
    X_max = np.max(X)

    # Normalize the array
    X_norm = (X - X_min) / (X_max - X_min)

    return X_norm

    #raise NotImplementedError()

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0.55555556, 0.66666667, 0.77777778],
       [0.88888889, 1.        , 0.        ]])

In [95]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)

AssertionError: 